services:
  myfeedback.backend:
    image: ${DOCKER_REGISTRY-}myfeedbackbackend
    build:
      context: .
      dockerfile: MyFeedback.Backend/Dockerfile
    networks:
      - proxybackend

  myfeedback.login:
    image: ${DOCKER_REGISTRY-}myfeedbacklogin
    build:
      context: .
      dockerfile: MyFeedback.Login/Dockerfile
    networks:
    - proxybackend
      
  mailcatcher:
    image: haravich/fake-smtp-server
    networks:
      - proxybackend

  myfeedback.proxybackend:
    image: ${DOCKER_REGISTRY-}myfeedbackproxybackend
    build:
      context: .
      dockerfile: MyFeedback.ProxyBackend/Dockerfile
    networks:
      - proxybackend

  myfeedback.ui:
    image: ${DOCKER_REGISTRY-}myfeedbackui
    build:
      context: .
      dockerfile: MyFeedback.UI/Dockerfile

networks:
  proxybackend:
     name: proxybackend
     driver: bridge

